title: Sherry' blog
author: Sherry
email: Sherry AT hotmail DOT com
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
github_username:  sherry725

defaults:
  -
    scope:
      path: "posts" #Indicate foler of posts 
    values:
      layout: "default"
      theme: minima


# Build settings
permalink: /:title.html
excerpt_separator: "<!-- more -->"





