title: Sherry's Blog 
author: sherry
email: shixinwu365 AT hotmail DOT com
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: ""
twitter_username: 
github_username:  

defaults:
  -
    scope:
      path: "posts" # 空字符串所有的文件。这里指posts文件夹
    values:
      layout: "default"
      theme: minima
      permalink: date  # 这是指博客文章的网址格式

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock