# Basic
title: Sherry
subtitle: 身体和灵魂，必须有一个在路上
welcome_message: Welcome Sherry's world
description: 分享技术，分享生活
creator: <a href="#">@Sherry</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog列表
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/sherry725/sherry725.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}


