# Basic
title: Sherry's Blog
subtitle: Think Free
welcome_message: Welcome to Sherry's Blog
description: enjoy life
creator: <a href="#">@Sherry</a>

defaults:
  -
    scope:
      path: "posts" # 空字符串所有的文件。这里指posts文件夹
    values:
      layout: "default"
      theme: minima
      permalink: date  # 这是指博客文章的网址格式

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock